name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: install
        run: |
          /bin/bash -c "$(curl -fsSL https://cli.moonbitlang.com/ubuntu_x86_64_moon_setup.sh)"
          echo "/home/runner/.moon/bin" >> $GITHUB_PATH

      - name: moon check
        run: moon check

      # - name: moon info
      #   run: |
      #     moon info
      #     git diff --exit-code

      - name: moon test
        run: |
          moon test
          moon test --target js

      # - name: moon bundle
      #   run: moon bundle

      # - name: check core size
      #   run: ls -alh `find ./target/bundle -name *.core`

      - name: format diff
        run: |
          moon fmt
          git diff
